### ISSUE TITLE
답안 PR 자동 병합 시기

### ISSUE THREAD

**Issue by findawayer** [smh-algorithms/algorithms#32]
기존엔 매주 일요일 정해진 시각에 모든 PR을 자동 병합하도록 설정했는데요. 1주일분 답안을 모아 주말에 제출하면, 다른 참가자가 그 답안을 리뷰할 시간이 길어도 24시간밖에 없더라구요. 그래서 일요일 AM 9시였던 병합시각을 PM 4시로 옮겨봤지만 이것도 부족할 것 같단 생각이 들어 이슈를 열었습니다.

제안하고 싶은 내용은 아래와 같습니다.

- 모든 PR은 최소 1개의 리뷰가 등록된 후, 그 다음 일요일 PM 4시에 자동으로 병합.
- 리뷰가 등록되지 않은 경우 병합되지 않은 상태로 계속 남음.

여기서 '리뷰'란 간단하게 아이디어가 맘에 든다는 멘트나, 이 부분은 무슨 뜻이죠? 같은 질문을 포함합니다. 참가하시는 분들의 의견을 듣고 싶어요.

**Comment by lunar-** [comment]
@findawayer 님 의견에 동의합니다. 추가로 몇 개 이상의 approve 를 받으면 특정 날짜에 병합되는 것도 생각해봤습니다. 그치만 가급적 의견교환을 활발히 할 수 있도록 리뷰가 merge 기준이 되는게 더 좋을 것 같아요.

**Comment by findawayer** [comment]
approve도 좋은 생각이에요. 커뮤니티 멤버가 늘어나면 approve를 활용하는 것도 생각해 볼 수 있을 것 같아요.
